version: 2

jobs:
  build:
    working_directory: ~/perms
    docker:
      - image: node:8
    steps:
      - checkout
      - restore_cache:
          key: perms-{{ checksum "yarn.lock" }}
      - run:
          name: System information
          command: |
            echo "Node $(node -v)"
            echo "Yarn v$(yarn --version)"
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Lint (Stylint)
          command: ./node_modules/.bin/stylint src
      - run:
          name: Lint (ESLint)
          command: |
            ./node_modules/.bin/eslint . --parser babel-eslint --ext .js,.jsx
      - save_cache:
          key: perms-{{ checksum "yarn.lock" }}
          paths:
            - ~/perms/node_modules
            - ~/.cache/yarn
  deploy:
    working_directory: ~/perms
    docker:
      - image: node:8
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Build
          command: |
            yarn build
            cd build
            git init
            git remote add origin git@github.com:geta6/perms.git
            echo 'www.permsproject.com' > CNAME
            git checkout -b gh-pages
            git add .
            git commit -am 'Release'
            git push -fu origin gh-pages

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
